### ISSUE TITLE
As a driver, I want to use my phone's bluetooth so that my phone can send/receive data with the OBD adapter.

### ISSUE THREAD

**Issue by LiveSatomi** [LTT-Gatech/CarCareAndroid#19]
## Task Details
- [x] Initialize bluetooth connection
- [x] Send an arbitrary message
- [x] Receive an arbitrary message
