### ISSUE TITLE
Create a SQLite Database backend

### ISSUE THREAD

**Issue by asasine** [LTT-Gatech/CarCareAndroid#37]
Start [here](https://developer.android.com/training/basics/data-storage/databases.html).

## Tasks
- [ ] Define schema #11  
- [ ] Create database using [SQLiteOpenHelper](https://developer.android.com/reference/android/database/sqlite/SQLiteOpenHelper.html)
- [ ] Read data from OBD #2 
- [ ] Put information into database
- [ ] Query information from database
- [ ] Update UI to display query result
- [ ] Persist database connection through application restarts

### Optional smaller tasks
- [ ] Option to delete from DB
- [ ] Option to update in DB
- [ ] Option to view raw data in DB

### Other notes
Start with Android samples such as [NotePad](https://github.com/android/platform_development/tree/master/samples/NotePad) or [SearchableDictionary](https://github.com/android/platform_development/tree/master/samples/SearchableDictionary).
