### ISSUE TITLE
Define database schema

### ISSUE THREAD

**Issue by asasine** [LTT-Gatech/CarCareAndroid#38]
## Tasks
- [x] Create human-readable map from OBD PID to English
- [x] Abstract OBD querying process #2 
- [x] Convert responses to English (with units)
- [x] Add responses to a View
