### ISSUE TITLE
As a user, I want to register an account so I can access features.

### ISSUE THREAD

**Issue by asasine** [LTT-Gatech/CarCareAndroid#5]
Easiest to be done by authenticating with a 3rd party API such as Google, Facebook, etc.

## Task Details
- [x] Design login page
- [x] Add 3rd party API
- [x] Redirect to home page after login
