### ISSUE TITLE
As a user, I want to login so that I can see my vehicle's statistics

### ISSUE THREAD

**Issue by asasine** [LTT-Gatech/CarCareAndroid#6]
## Task Details
- [x] Design login page
- [x] Add 3rd party API
- [x] Redirect to home page after login
