### ISSUE TITLE
As a user, I want to be able to log in to my account from different devices so I can access data from different locations

### ISSUE THREAD

**Issue by asasine** [LTT-Gatech/CarCareAndroid#7]
## Task Details
- [x] Design login page
- [x] Add 3rd party API
- [x] Redirect to home page after login
- [ ] Store data in the cloud #18
