### ISSUE TITLE
As a user, I want to manage multiple vehicles in the same user’s app so that I can track all of my vehicles in the same location

### ISSUE THREAD

**Issue by asasine** [LTT-Gatech/CarCareAndroid#9]
## Task Details
- [ ] Design "add a vehicle" page
- [ ] Be able to switch vehicles #10 
- [ ] Update home screen to show current vehicle #11
